### ISSUE TITLE
Used%/Free% doesn't add up to 100

### ISSUE THREAD

**Issue by hbons** [bbbbbr/romusage#12]
![Screenshot 2023-08-05 10 23 35](https://github.com/bbbbbr/romusage/assets/103326/f40381b6-bff1-4417-801c-ac755e55d602)

This is probably due to rounding? Could be fixed by displaying one of the values as 100 minus the other value.

**Comment by bbbbbr** [comment]
Thanks, I somehow never noticed this :smile: 

You can pick up a new build with the change from the action run linked below (requires logged in to gh) since it might be a while before I put out a new release.
https://github.com/bbbbbr/romusage/actions/runs/5779700633

**Comment by hbons** [comment]
Thanks! And thanks a lot for this great tool!
