### ISSUE TITLE
-a output stops after a space

### ISSUE THREAD

**Issue by evie-calico** [bbbbbr/romusage#8]
RGBDS section names may have a space in them, but romusage will only print the first word before stopping on the space. For example, "OAM DMA" is just printed as "OAM".

You can see the map file below compared to romusage's output.
![image](https://user-images.githubusercontent.com/14899090/200018457-4539b73e-f2e6-4f0a-ac36-ba495f1a6316.png)

**Comment by bbbbbr** [comment]
Thanks for opening this. I implemented it slightly different than suggested, but appreciate the proposed changes as an example.
